public class ResolveMetadataFromPackages {

    public void playground() {
        efaxapp__eFax_Fields__c efaxappObj = null;
        likh__TestDeploySObject__c likhObj = null;
        npe5__Affiliation__c npe5Obj = null;
        rh2__PS_Describe__c rh2Obj = null;

        likh.LikhPack_Class likhClass1 = null;
        rh2.CommonUtil rh2Class = null;
        ssv4.coreDebugLog ssv4Class = null;
    }
}